name: expenses_app
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.4  
  get_it: ^8.0.3
  equatable: ^2.0.7
  flutter_bloc: ^8.1.6
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true